version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./:/process
      - /process/node_modules
    ports:
      - "3333:3333"
    env_file:
      - .env
    networks:
      - secjs-network
    restart: on-failure

networks:
  secjs-network:
    external:
      name: secjs-network
