version: '3'

services:
  redis-nestjs-nosql:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - lkp_dev
  mongo-nestjs-nosql:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - lkp_dev
  nestjs-nosql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - lkp_dev
    restart: on-failure
    depends_on:
      - "redis-nestjs-nosql"
      - "mongo-nestjs-nosql"

networks:
  lkp_dev:
    external:
      name: lkp_dev
